### PR TITLE
Feature/design register screen

### PR DESCRIPTION
**Pull request by VictorAgovski**

### CODE REVIEW

**Comment by HristoPetkov94** [comment]
image


remove the old signup

**Comment by HristoPetkov94** [comment]
when bigger screen radio button is not styled

image

**Comment by HristoPetkov94** [comment]
the button is not working

image

**Comment by HristoPetkov94** [comment]
image

**Comment by HristoPetkov94** [comment]
image

**Comment by VictorAgovski** [comment]
> image

I will do this in a new branch

**Comment by VictorAgovski** [comment]
> image

I didn't make this screen

**Review by HristoPetkov94 — APPROVED** [review]

**Pull request merged**
